version: "2"
services:
  postgres:
    image: postgres
    expose:
      - "5432"
    environment:
      - POSTGRES_DB=intrigue_prod
  redis:
    image: redis
    expose:
      - "6379"
  web:
    build: .
    ports:
      - "7778:7778"
    links:
      - redis
      - postgres
    environment:
      - INTRIGUE_ENV=docker
      - REDIS_URI=redis://redis:6379/
  worker:
    build: .
    links:
      - redis
      - postgres
    environment:
      - INTRIGUE_ENV=docker
      - REDIS_URI=redis://redis:6379/
